media:
  input: public/images/menu
  output: /public/images/menu
  label: Menu photos
content:
  - name: menu-items
    label: Menu Items
    path: src/data/menuData.json
    type: file
    list: true
    format: json
    fields:
      - name: name
        label: Name
        type: string
      - name: description
        label: Description
        type: string
        description: Will be provused for any page with no description.
      - name: price
        label: Price
        type: number
      - name: category
        label: Category
        type: select
        options:
          values: [ BBQ Gerechten, Onze Gerechten, Mezze, Soepen, Sandwiches, Menu Combinaties, Dranken ]
      - name: popular
        label: Is popular
        type: boolean
      - name: serves
        label: Serves
        type: number
      - name: image
        label: Image
        type: image