media:
  input: ./public/images/menu
  output: ./public/images/menu
  path: public/images/menu
  label: Menu items
content:
  - name: menu-items
    label: Menu Items
    path: src/data/menuData.json
    type: file
    list: true
    format: json
    fields:
      - name: name
        label: Item name
        type: string
      - name: description
        label: Item description
        type: string
        description: Will be provused for any page with no description.
      - name: price
        label: Item price
        type: number
      - name: popular
        label: Is popular
        type: boolean
      - name: image
        label: Item image
        type: image
        options:
          path: .